---
- name: Configure etcd
  hosts: oo_etcd_to_config
  any_errors_fatal: true
  roles:
  - role: openshift_etcd
    etcd_peers: "{{ groups.oo_etcd_to_config | default([], true) }}"
    etcd_ca_host: "{{ groups.oo_masters_to_config.0 }}"
    etcd_certificates_etcd_hosts: "{{ groups.oo_etcd_to_config | default([], true) }}"
    openshift_ca_host: "{{ groups.oo_masters_to_config.0 }}"
    openshift_master_hostnames: "{{ hostvars
                                    | oo_select_keys(groups['oo_masters_to_config'] | default([]))
                                    | oo_collect('openshift.common.all_hostnames')
                                    | oo_flatten | unique }}"
  - role: nickhammond.logrotate
