---
- include: ../openshift-cluster/initialize_groups.yml
  tags:
    - always

- include: ../../common/openshift-cluster/evaluate_groups.yml

- include: ../../common/openshift-management/add_container_provider.yml
