---
- name: Create directory /usr/share/nuage-openshift-monitor
  become: true
  file: path=/usr/share/nuage-openshift-monitor state=directory

- name: Create the log directory
  become: true
  file: path={{ nuage_openshift_monitor_log_dir }} state=directory

- name: Install Nuage Openshift Monitor 
  become: true
  yum: name={{ nuage_openshift_rpm }} state=present

- name: Run the service account creation script
  become: true
  script: serviceaccount.sh --server={{ openshift.master.api_url }} --output-cert-dir={{ cert_output_dir }} --master-cert-dir={{ openshift_master_config_dir }}

- name: Download the certs and keys
  become: true
  fetch: src={{ cert_output_dir }}/{{ item }} dest=/tmp/{{ item }} flat=yes
  with_items:
        - ca.crt
        - nuage.crt
        - nuage.key
        - nuage.kubeconfig

- include: certificates.yml

- name: Create nuage-openshift-monitor.yaml
  become: true
  template: src=nuage-openshift-monitor.j2 dest=/usr/share/nuage-openshift-monitor/nuage-openshift-monitor.yaml owner=root mode=0644
  notify:
    - restart master
    - restart master api
    - restart master controllers
    - restart nuage-openshift-monitor
